// <auto-generated />
using System;
using CleanArchDemo.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchDemo.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchDemo.Domain.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 3, 28, 8, 17, 40, 784, DateTimeKind.Utc).AddTicks(4375),
                            Description = "Ducimus nobis maxime in ipsum ducimus veritatis dolorem.",
                            ImageUrl = "https://picsum.photos/640/480/?image=329",
                            Name = "Lakin Inc Villa",
                            Occupancy = 8,
                            Price = 2615.2129645656337,
                            Sqft = 691,
                            UpdatedDate = new DateTime(2023, 4, 14, 8, 17, 40, 784, DateTimeKind.Utc).AddTicks(4375)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 7, 8, 19, 20, 37, 48, DateTimeKind.Utc).AddTicks(5532),
                            Description = "Ut quas sit reiciendis fugit cum.",
                            ImageUrl = "https://picsum.photos/640/480/?image=543",
                            Name = "Cummerata LLC Villa",
                            Occupancy = 1,
                            Price = 1400.308354681328,
                            Sqft = 1893,
                            UpdatedDate = new DateTime(2024, 7, 24, 19, 20, 37, 48, DateTimeKind.Utc).AddTicks(5532)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 11, 11, 23, 41, 34, 121, DateTimeKind.Utc).AddTicks(2185),
                            Description = "Qui non voluptatem iusto.",
                            ImageUrl = "https://picsum.photos/640/480/?image=432",
                            Name = "Padberg, Balistreri and Batz Villa",
                            Occupancy = 2,
                            Price = 3044.2899776326053,
                            Sqft = 1196,
                            UpdatedDate = new DateTime(2023, 12, 6, 23, 41, 34, 121, DateTimeKind.Utc).AddTicks(2185)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 6, 3, 22, 40, 45, 627, DateTimeKind.Utc).AddTicks(5534),
                            Description = "Facilis deleniti libero excepturi modi enim.",
                            ImageUrl = "https://picsum.photos/640/480/?image=340",
                            Name = "Cummerata LLC Villa",
                            Occupancy = 3,
                            Price = 1107.1005729634032,
                            Sqft = 1682,
                            UpdatedDate = new DateTime(2023, 6, 12, 22, 40, 45, 627, DateTimeKind.Utc).AddTicks(5534)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 11, 27, 2, 6, 47, 196, DateTimeKind.Utc).AddTicks(4996),
                            Description = "Nostrum architecto adipisci et.",
                            ImageUrl = "https://picsum.photos/640/480/?image=688",
                            Name = "Murphy, Frami and Mayer Villa",
                            Occupancy = 3,
                            Price = 1394.2574872886944,
                            Sqft = 1536,
                            UpdatedDate = new DateTime(2022, 12, 3, 2, 6, 47, 196, DateTimeKind.Utc).AddTicks(4996)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 3, 8, 12, 15, 16, 780, DateTimeKind.Utc).AddTicks(8825),
                            Description = "Accusantium in consequatur ut sed.",
                            ImageUrl = "https://picsum.photos/640/480/?image=595",
                            Name = "Tremblay, Bednar and Bruen Villa",
                            Occupancy = 9,
                            Price = 3024.4695072059035,
                            Sqft = 2964,
                            UpdatedDate = new DateTime(2023, 3, 27, 12, 15, 16, 780, DateTimeKind.Utc).AddTicks(8825)
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 12, 22, 3, 37, 57, 560, DateTimeKind.Utc).AddTicks(5186),
                            Description = "Eum id assumenda necessitatibus necessitatibus cum.",
                            ImageUrl = "https://picsum.photos/640/480/?image=694",
                            Name = "Kovacek Inc Villa",
                            Occupancy = 1,
                            Price = 505.56398634883669,
                            Sqft = 4965,
                            UpdatedDate = new DateTime(2022, 12, 30, 3, 37, 57, 560, DateTimeKind.Utc).AddTicks(5186)
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 2, 13, 18, 25, 4, 257, DateTimeKind.Utc).AddTicks(8010),
                            Description = "Quia accusamus deleniti deleniti voluptatum officia.",
                            ImageUrl = "https://picsum.photos/640/480/?image=558",
                            Name = "Marquardt - Lind Villa",
                            Occupancy = 4,
                            Price = 2970.8013763647423,
                            Sqft = 1861,
                            UpdatedDate = new DateTime(2023, 2, 23, 18, 25, 4, 257, DateTimeKind.Utc).AddTicks(8010)
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 3, 6, 23, 11, 37, 65, DateTimeKind.Utc).AddTicks(8657),
                            Description = "Exercitationem voluptate ex quo.",
                            ImageUrl = "https://picsum.photos/640/480/?image=957",
                            Name = "Hirthe - Metz Villa",
                            Occupancy = 7,
                            Price = 3770.0430866792803,
                            Sqft = 703,
                            UpdatedDate = new DateTime(2023, 3, 18, 23, 11, 37, 65, DateTimeKind.Utc).AddTicks(8657)
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 10, 4, 14, 8, 7, 267, DateTimeKind.Utc).AddTicks(9792),
                            Description = "Magni non sunt vitae.",
                            ImageUrl = "https://picsum.photos/640/480/?image=1082",
                            Name = "Heidenreich, Fay and Senger Villa",
                            Occupancy = 10,
                            Price = 951.048688663809,
                            Sqft = 2255,
                            UpdatedDate = new DateTime(2024, 10, 22, 14, 8, 7, 267, DateTimeKind.Utc).AddTicks(9792)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
